// <auto-generated />
using System;
using Alfateam.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alfateam.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221226083214_CallRequests")]
    partial class CallRequests
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Alfateam.Database.Models.CallRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WasCall")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("CallRequests");
                });

            modelBuilder.Entity("Alfateam.Database.Models.General.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconPath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsShown")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.NewPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("Watches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("NewPosts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostHeading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NewPostId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NewPostId");

                    b.ToTable("PostHeadings");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NewPostId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("PostSliderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewPostId");

                    b.HasIndex("PostSliderId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NewPostId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NewPostId");

                    b.ToTable("PostParagraphs");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostSlider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NewPostId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewPostId");

                    b.ToTable("PostSliders");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NewPostId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewPostId");

                    b.ToTable("PostVideos");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Alfateam.Database.Models.PortfolioCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioCategories");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Portfolios.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Portfolios.PortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioImages");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.Property<int>("Watches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Promotions.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RightImgPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Promotions.PromotionDescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionDescriptionItems");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SiteFrontend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ErrorPagesId")
                        .HasColumnType("int");

                    b.Property<int>("GeneralTextsId")
                        .HasColumnType("int");

                    b.Property<int>("LandingTextsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ErrorPagesId");

                    b.HasIndex("GeneralTextsId");

                    b.HasIndex("LandingTextsId");

                    b.ToTable("SiteFrontends");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.ErrorPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ErrorPages");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GeneralTexts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.LandingTexts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LandingTexts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Teammate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teammates");
                });

            modelBuilder.Entity("Alfateam.Database.Models.TranslationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ErrorPagesId")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorPagesId1")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorPagesId2")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorPagesId3")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId1")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId10")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId11")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId12")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId13")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId14")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId15")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId16")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId2")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId3")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId4")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId5")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId6")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId7")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId8")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralTextsId9")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId1")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId10")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId11")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId12")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId13")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId14")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId15")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId16")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId17")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId18")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId19")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId2")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId20")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId21")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId3")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId4")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId5")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId6")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId7")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId8")
                        .HasColumnType("int");

                    b.Property<int?>("LandingTextsId9")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerId1")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId1")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId1")
                        .HasColumnType("int");

                    b.Property<int?>("PromotionDescriptionItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int?>("PromotionId1")
                        .HasColumnType("int");

                    b.Property<int?>("TeammateId")
                        .HasColumnType("int");

                    b.Property<int?>("TeammateId1")
                        .HasColumnType("int");

                    b.Property<int?>("TeammateId2")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ErrorPagesId");

                    b.HasIndex("ErrorPagesId1");

                    b.HasIndex("ErrorPagesId2");

                    b.HasIndex("ErrorPagesId3");

                    b.HasIndex("GeneralTextsId");

                    b.HasIndex("GeneralTextsId1");

                    b.HasIndex("GeneralTextsId10");

                    b.HasIndex("GeneralTextsId11");

                    b.HasIndex("GeneralTextsId12");

                    b.HasIndex("GeneralTextsId13");

                    b.HasIndex("GeneralTextsId14");

                    b.HasIndex("GeneralTextsId15");

                    b.HasIndex("GeneralTextsId16");

                    b.HasIndex("GeneralTextsId2");

                    b.HasIndex("GeneralTextsId3");

                    b.HasIndex("GeneralTextsId4");

                    b.HasIndex("GeneralTextsId5");

                    b.HasIndex("GeneralTextsId6");

                    b.HasIndex("GeneralTextsId7");

                    b.HasIndex("GeneralTextsId8");

                    b.HasIndex("GeneralTextsId9");

                    b.HasIndex("LandingTextsId");

                    b.HasIndex("LandingTextsId1");

                    b.HasIndex("LandingTextsId10");

                    b.HasIndex("LandingTextsId11");

                    b.HasIndex("LandingTextsId12");

                    b.HasIndex("LandingTextsId13");

                    b.HasIndex("LandingTextsId14");

                    b.HasIndex("LandingTextsId15");

                    b.HasIndex("LandingTextsId16");

                    b.HasIndex("LandingTextsId17");

                    b.HasIndex("LandingTextsId18");

                    b.HasIndex("LandingTextsId19");

                    b.HasIndex("LandingTextsId2");

                    b.HasIndex("LandingTextsId20");

                    b.HasIndex("LandingTextsId21");

                    b.HasIndex("LandingTextsId3");

                    b.HasIndex("LandingTextsId4");

                    b.HasIndex("LandingTextsId5");

                    b.HasIndex("LandingTextsId6");

                    b.HasIndex("LandingTextsId7");

                    b.HasIndex("LandingTextsId8");

                    b.HasIndex("LandingTextsId9");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("PartnerId1");

                    b.HasIndex("PortfolioCategoryId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("PortfolioId1");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId1");

                    b.HasIndex("PromotionDescriptionItemId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("PromotionId1");

                    b.HasIndex("TeammateId");

                    b.HasIndex("TeammateId1");

                    b.HasIndex("TeammateId2");

                    b.ToTable("TranslationItems");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.NewPost", b =>
                {
                    b.HasOne("Alfateam.Database.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostHeading", b =>
                {
                    b.HasOne("Alfateam.Database.Models.NewPosts.NewPost", null)
                        .WithMany("Headings")
                        .HasForeignKey("NewPostId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostImage", b =>
                {
                    b.HasOne("Alfateam.Database.Models.NewPosts.NewPost", null)
                        .WithMany("Images")
                        .HasForeignKey("NewPostId");

                    b.HasOne("Alfateam.Database.Models.NewPosts.PostSlider", null)
                        .WithMany("Images")
                        .HasForeignKey("PostSliderId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostParagraph", b =>
                {
                    b.HasOne("Alfateam.Database.Models.NewPosts.NewPost", null)
                        .WithMany("Paragraphs")
                        .HasForeignKey("NewPostId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostSlider", b =>
                {
                    b.HasOne("Alfateam.Database.Models.NewPosts.NewPost", null)
                        .WithMany("Sliders")
                        .HasForeignKey("NewPostId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostVideo", b =>
                {
                    b.HasOne("Alfateam.Database.Models.NewPosts.NewPost", null)
                        .WithMany("Videos")
                        .HasForeignKey("NewPostId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Portfolios.Portfolio", b =>
                {
                    b.HasOne("Alfateam.Database.Models.PortfolioCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Portfolios.PortfolioImage", b =>
                {
                    b.HasOne("Alfateam.Database.Models.Portfolios.Portfolio", null)
                        .WithMany("Images")
                        .HasForeignKey("PortfolioId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Promotions.PromotionDescriptionItem", b =>
                {
                    b.HasOne("Alfateam.Database.Models.Promotions.Promotion", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("PromotionId");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SiteFrontend", b =>
                {
                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.ErrorPages", "ErrorPages")
                        .WithMany()
                        .HasForeignKey("ErrorPagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", "GeneralTexts")
                        .WithMany()
                        .HasForeignKey("GeneralTextsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", "LandingTexts")
                        .WithMany()
                        .HasForeignKey("LandingTextsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorPages");

                    b.Navigation("GeneralTexts");

                    b.Navigation("LandingTexts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.TranslationItem", b =>
                {
                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.ErrorPages", null)
                        .WithMany("Texts403")
                        .HasForeignKey("ErrorPagesId");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.ErrorPages", null)
                        .WithMany("Texts404")
                        .HasForeignKey("ErrorPagesId1");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.ErrorPages", null)
                        .WithMany("TextsNuhuyaDescription")
                        .HasForeignKey("ErrorPagesId2");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.ErrorPages", null)
                        .WithMany("TextsNuhuyaTitle")
                        .HasForeignKey("ErrorPagesId3");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("AddedAt")
                        .HasForeignKey("GeneralTextsId");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("AllPortfolios")
                        .HasForeignKey("GeneralTextsId1");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("OurWorks")
                        .HasForeignKey("GeneralTextsId10");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Partners")
                        .HasForeignKey("GeneralTextsId11");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("PublishedAt")
                        .HasForeignKey("GeneralTextsId12");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("ServicesPrice")
                        .HasForeignKey("GeneralTextsId13");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("SocialNetworks")
                        .HasForeignKey("GeneralTextsId14");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Team")
                        .HasForeignKey("GeneralTextsId15");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Watches")
                        .HasForeignKey("GeneralTextsId16");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("AllRightsReserved")
                        .HasForeignKey("GeneralTextsId2");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Categories")
                        .HasForeignKey("GeneralTextsId3");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Close")
                        .HasForeignKey("GeneralTextsId4");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Contacts")
                        .HasForeignKey("GeneralTextsId5");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Main")
                        .HasForeignKey("GeneralTextsId6");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("Navigation")
                        .HasForeignKey("GeneralTextsId7");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("NewPortfolioLabel")
                        .HasForeignKey("GeneralTextsId8");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", null)
                        .WithMany("News")
                        .HasForeignKey("GeneralTextsId9");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("CompanyName")
                        .HasForeignKey("LandingTextsId");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("Contacts")
                        .HasForeignKey("LandingTextsId1");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("NewsMore")
                        .HasForeignKey("LandingTextsId10");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("Order")
                        .HasForeignKey("LandingTextsId11");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("OrderCompleted")
                        .HasForeignKey("LandingTextsId12");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("OrderNow")
                        .HasForeignKey("LandingTextsId13");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("OurLastPortfolios")
                        .HasForeignKey("LandingTextsId14");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("OurPortfolios")
                        .HasForeignKey("LandingTextsId15");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("Send")
                        .HasForeignKey("LandingTextsId16");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("StartBusiness")
                        .HasForeignKey("LandingTextsId17");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("StartBusinessDescriptions")
                        .HasForeignKey("LandingTextsId18");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("WeAcceptPayments")
                        .HasForeignKey("LandingTextsId19");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("ContactsPlaceholder")
                        .HasForeignKey("LandingTextsId2");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("YourBudget")
                        .HasForeignKey("LandingTextsId20");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("YourName")
                        .HasForeignKey("LandingTextsId21");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("DescribeJob")
                        .HasForeignKey("LandingTextsId3");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("DescribeJobPlaceholder")
                        .HasForeignKey("LandingTextsId4");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("DiscoverNews")
                        .HasForeignKey("LandingTextsId5");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("MakeOrder")
                        .HasForeignKey("LandingTextsId6");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("MorePortfolios")
                        .HasForeignKey("LandingTextsId7");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("News")
                        .HasForeignKey("LandingTextsId8");

                    b.HasOne("Alfateam.Database.Models.SitePagesTexts.LandingTexts", null)
                        .WithMany("NewsDetails")
                        .HasForeignKey("LandingTextsId9");

                    b.HasOne("Alfateam.Database.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfateam.Database.Models.Partner", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("PartnerId");

                    b.HasOne("Alfateam.Database.Models.Partner", null)
                        .WithMany("Titles")
                        .HasForeignKey("PartnerId1");

                    b.HasOne("Alfateam.Database.Models.PortfolioCategory", null)
                        .WithMany("Captions")
                        .HasForeignKey("PortfolioCategoryId");

                    b.HasOne("Alfateam.Database.Models.Portfolios.Portfolio", null)
                        .WithMany("Captions")
                        .HasForeignKey("PortfolioId");

                    b.HasOne("Alfateam.Database.Models.Portfolios.Portfolio", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("PortfolioId1");

                    b.HasOne("Alfateam.Database.Models.Post", null)
                        .WithMany("Captions")
                        .HasForeignKey("PostId");

                    b.HasOne("Alfateam.Database.Models.Post", null)
                        .WithMany("Contents")
                        .HasForeignKey("PostId1");

                    b.HasOne("Alfateam.Database.Models.Promotions.PromotionDescriptionItem", null)
                        .WithMany("Texts")
                        .HasForeignKey("PromotionDescriptionItemId");

                    b.HasOne("Alfateam.Database.Models.Promotions.Promotion", null)
                        .WithMany("Captions")
                        .HasForeignKey("PromotionId");

                    b.HasOne("Alfateam.Database.Models.Promotions.Promotion", null)
                        .WithMany("Prices")
                        .HasForeignKey("PromotionId1");

                    b.HasOne("Alfateam.Database.Models.Teammate", null)
                        .WithMany("MiddleDescriptions")
                        .HasForeignKey("TeammateId");

                    b.HasOne("Alfateam.Database.Models.Teammate", null)
                        .WithMany("Positions")
                        .HasForeignKey("TeammateId1");

                    b.HasOne("Alfateam.Database.Models.Teammate", null)
                        .WithMany("Titles")
                        .HasForeignKey("TeammateId2");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.NewPost", b =>
                {
                    b.Navigation("Headings");

                    b.Navigation("Images");

                    b.Navigation("Paragraphs");

                    b.Navigation("Sliders");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Alfateam.Database.Models.NewPosts.PostSlider", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Partner", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Alfateam.Database.Models.PortfolioCategory", b =>
                {
                    b.Navigation("Captions");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Portfolios.Portfolio", b =>
                {
                    b.Navigation("Captions");

                    b.Navigation("Descriptions");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Post", b =>
                {
                    b.Navigation("Captions");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Promotions.Promotion", b =>
                {
                    b.Navigation("Captions");

                    b.Navigation("Descriptions");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Promotions.PromotionDescriptionItem", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.ErrorPages", b =>
                {
                    b.Navigation("Texts403");

                    b.Navigation("Texts404");

                    b.Navigation("TextsNuhuyaDescription");

                    b.Navigation("TextsNuhuyaTitle");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.GeneralTexts", b =>
                {
                    b.Navigation("AddedAt");

                    b.Navigation("AllPortfolios");

                    b.Navigation("AllRightsReserved");

                    b.Navigation("Categories");

                    b.Navigation("Close");

                    b.Navigation("Contacts");

                    b.Navigation("Main");

                    b.Navigation("Navigation");

                    b.Navigation("NewPortfolioLabel");

                    b.Navigation("News");

                    b.Navigation("OurWorks");

                    b.Navigation("Partners");

                    b.Navigation("PublishedAt");

                    b.Navigation("ServicesPrice");

                    b.Navigation("SocialNetworks");

                    b.Navigation("Team");

                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Alfateam.Database.Models.SitePagesTexts.LandingTexts", b =>
                {
                    b.Navigation("CompanyName");

                    b.Navigation("Contacts");

                    b.Navigation("ContactsPlaceholder");

                    b.Navigation("DescribeJob");

                    b.Navigation("DescribeJobPlaceholder");

                    b.Navigation("DiscoverNews");

                    b.Navigation("MakeOrder");

                    b.Navigation("MorePortfolios");

                    b.Navigation("News");

                    b.Navigation("NewsDetails");

                    b.Navigation("NewsMore");

                    b.Navigation("Order");

                    b.Navigation("OrderCompleted");

                    b.Navigation("OrderNow");

                    b.Navigation("OurLastPortfolios");

                    b.Navigation("OurPortfolios");

                    b.Navigation("Send");

                    b.Navigation("StartBusiness");

                    b.Navigation("StartBusinessDescriptions");

                    b.Navigation("WeAcceptPayments");

                    b.Navigation("YourBudget");

                    b.Navigation("YourName");
                });

            modelBuilder.Entity("Alfateam.Database.Models.Teammate", b =>
                {
                    b.Navigation("MiddleDescriptions");

                    b.Navigation("Positions");

                    b.Navigation("Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
